version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - REACT_APP_DEBUG=TRUE
    ports:
      - 3000:3000
    container_name: jobsearcher-ui